### ISSUE TITLE
생체인증 권한 거부 알림 버그

### ISSUE THREAD

**Issue by pio-noncelab** [noncelab/coconut_vault#20]
# ❌ Bug - FaceId 권한 요청 거부 버그

### 📝 Description

---

앱 최초 실행 후 핀번호 저장 직후에 권한 허용 팝업이 뜨는게 정상이나
'권한 거부됨' 알림이 바로 발생

### 📱 Environment

---

OS
- [x] iOS
- [x] Android

### ✅ To Do List

---

- [x] 버그가 발생하는 원인 파악
- [x] 정상 작동되도록 버그 해결

### 📚Etc

---

특이사항

**Comment by Ella-noncelab** [comment]
커밋번호: c500e3e8764ee22e4190c122d88122909520a53a

생체인증 요청 전, 기기의 생체인증 가능 여부를 확인하는 로직이 누락되어 있었습니다.
